[package]
name = "heikousen_rusty"
version = "0.1.0"
authors = ["Giymo11 <gizmo.head@yahoo.de>"]

[dependencies]
vulkano = "0.9"
vulkano-shader-derive = "0.9"
image = "0.19"
winit = "0.11.0"
vulkano-win = "0.9"
cgmath = "0.14.1"
time = "0.1.37"